version: '3'
services:
    db-psql:
        container_name: "pokemon-team"
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB_NAME}
        volumes:
            - ~/Docker/pokemon/postgresql/data:/var/lib/postgresql/data
        ports:
            - ${PG_PORT}:5432
